---
apiVersion: v1
kind: Config
clusters:
- name: "cluster"
  cluster:
    server: "{{ cluster_server }}"
    certificate-authority-data: "{{ cluster_ca_crt_b64 }}"
    api-version: v1

users:
- name: "cluster-user"
  user:
    token: "{{ cluster_token }}"

contexts:
- name: "cluster"
  context:
    user: "cluster-user"
    cluster: "cluster"

current-context: "cluster"
