- name: Apply ingress controller definitions
  k8s:
    state: "{{ deploy_state }}"
    definition: "{{ item }}"
  loop: "{{ lookup('template', 'ingress-controller.yml') | from_yaml_all | list }}"

- name: Apply cert-manager definitions
  k8s:
    state: "{{ deploy_state }}"
    definition: "{{ item }}"
  loop: "{{ lookup('template', 'cert-manager.yml') | from_yaml_all | list }}"

- name: Apply cert-issuers definitions
  k8s:
    state: "{{ deploy_state }}"
    definition: "{{ item }}"
  loop: "{{ lookup('template', 'cluster-issuers.yml') | from_yaml_all | list }}"

